// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/event-forecast": {
            "post": {
                "description": "Returns weather risk assessment for a given event location and time window.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "event"
                ],
                "summary": "Get event weather forecast and risk classification",
                "parameters": [
                    {
                        "description": "Event forecast request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.EventForecastRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.EventForecastResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.EventForecastRequest": {
            "type": "object",
            "required": [
                "end_time",
                "location",
                "name",
                "start_time"
            ],
            "properties": {
                "end_time": {
                    "type": "string"
                },
                "location": {
                    "$ref": "#/definitions/model.Location"
                },
                "name": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                }
            }
        },
        "model.EventForecastResponse": {
            "type": "object",
            "properties": {
                "classification": {
                    "type": "string"
                },
                "forecast_window": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.HourlyForecast"
                    }
                },
                "reasons": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "severity": {
                    "type": "integer"
                },
                "summary": {
                    "type": "string"
                }
            }
        },
        "model.HourlyForecast": {
            "type": "object",
            "properties": {
                "precip_mm": {
                    "type": "number"
                },
                "rain_prob": {
                    "type": "integer"
                },
                "time": {
                    "type": "string"
                },
                "weather": {
                    "type": "string"
                },
                "wind_kmh": {
                    "type": "number"
                }
            }
        },
        "model.Location": {
            "type": "object",
            "required": [
                "latitude",
                "longitude"
            ],
            "properties": {
                "latitude": {
                    "type": "number"
                },
                "longitude": {
                    "type": "number"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "EventWeatherGuard API",
	Description:      "API for weather risk assessment for outdoor events.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
